server:
  port: 8761
spring:
  application:
    name: eureka-admin-server
  boot:
    admin:
      context-path: /admin

  security:
    user:
      name: admin
      password: admin
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: https://admin:admin@localhost:8761/eureka
  instance:
    prefer-ip-address: true
management:
  endpoints:
    web:
      exposure:
        include:
        - '*'
      